-- ============================================================
-- Portfolio Database Schema
-- Exported from Supabase project: portfolio (tmdeznfqdcyarrnixday)
-- Postgres 17
-- Generated: 2026-07-19
-- Portable to any standard PostgreSQL provider
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Table: users
-- ------------------------------------------------------------
CREATE TABLE users (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        varchar(255) NOT NULL,
    job_title                   varchar(255),
    email                       varchar(255) NOT NULL,
    hero_description            text,
    about_description           text,
    capabilities_description    text,
    about_title                 varchar(500),
    linkedin_url                varchar(500),
    github_url                  varchar(500),
    resume_url                  varchar(500),
    picture_url                 varchar(500),
    portfolio_name              varchar(255),
    is_active                   boolean DEFAULT false,
    CONSTRAINT users_portfolioname_key UNIQUE (portfolio_name)
);

CREATE INDEX idx_users_email ON users USING btree (email);
CREATE INDEX idx_users_active ON users USING btree (id) WHERE (is_active = true);
CREATE INDEX idx_users_portfolio_name_active ON users USING btree (portfolio_name) WHERE (is_active = true);

-- ------------------------------------------------------------
-- Table: auth_codes
-- ------------------------------------------------------------
CREATE TABLE auth_codes (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash   varchar(255) NOT NULL,
    created_at  timestamptz DEFAULT now(),
    expires_at  timestamptz DEFAULT (now() + interval '00:10:00')
);

CREATE INDEX idx_auth_codes_hash ON auth_codes USING btree (code_hash);
CREATE INDEX idx_auth_codes_expires_at ON auth_codes USING btree (expires_at);

-- ------------------------------------------------------------
-- Table: experiences
-- ------------------------------------------------------------
CREATE TABLE experiences (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES users(id) ON DELETE CASCADE,
    role        varchar(255),
    period      varchar(100),
    description text,
    company     varchar(255)
);

CREATE INDEX idx_experiences_user_id ON experiences USING btree (user_id);

-- ------------------------------------------------------------
-- Table: education
-- ------------------------------------------------------------
CREATE TABLE education (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES users(id) ON DELETE CASCADE,
    institution varchar(255) NOT NULL,
    degree      varchar(255),
    period      varchar(255),
    grade       varchar(255),
    location    varchar(255),
    description text,
    sort_order  integer DEFAULT 0
);

CREATE INDEX idx_education_user_id ON education USING btree (user_id);
CREATE INDEX idx_education_user_sort ON education USING btree (user_id, sort_order);

-- ------------------------------------------------------------
-- Table: courses
-- ------------------------------------------------------------
CREATE TABLE courses (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer REFERENCES users(id) ON DELETE CASCADE,
    title           varchar(255) NOT NULL,
    provider        varchar(255),
    credential_id   varchar(255),
    certificate_url text,
    description     text,
    sort_order      integer DEFAULT 0,
    year            integer,
    type            varchar(20),
    hours           integer,
    CONSTRAINT courses_type_check CHECK (
        (type)::text = ANY (ARRAY[('course')::text, ('certificate')::text])
    )
);

CREATE INDEX idx_courses_user_id ON courses USING btree (user_id);
CREATE INDEX idx_courses_user_type ON courses USING btree (user_id, type);
CREATE INDEX idx_courses_user_sort ON courses USING btree (user_id, sort_order);

-- ------------------------------------------------------------
-- Table: projects
-- ------------------------------------------------------------
CREATE TABLE projects (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer REFERENCES users(id) ON DELETE CASCADE,
    title           varchar(255),
    client          varchar(255),
    role            varchar(255),
    year            integer,
    status          varchar(100),
    sort_order      integer,
    description     text,
    github_url      varchar(500),
    technologies    varchar(255),
    images          text[],
    live_url        text
);

CREATE INDEX idx_projects_user_id ON projects USING btree (user_id);
CREATE INDEX idx_projects_status ON projects USING btree (status);
CREATE INDEX idx_projects_user_status_sort ON projects USING btree (user_id, status, sort_order);
CREATE INDEX idx_projects_active ON projects USING btree (user_id, sort_order) WHERE ((status)::text = 'active'::text);

-- ------------------------------------------------------------
-- Table: skills
-- ------------------------------------------------------------
CREATE TABLE skills (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    name    varchar(100),
    type    varchar(10),
    CONSTRAINT check_type CHECK (
        (type)::text = ANY ((ARRAY['primary'::character varying, 'secondary'::character varying])::text[])
    ),
    CONSTRAINT unique_name UNIQUE (name, user_id)
);

CREATE INDEX idx_skills_user_id ON skills USING btree (user_id);
CREATE INDEX idx_skills_user_type ON skills USING btree (user_id, type);

-- ============================================================
-- Functions
-- ============================================================

CREATE OR REPLACE FUNCTION reorder_projects_for_user(target_user_id integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM projects
        WHERE user_id = target_user_id
    )
    UPDATE projects
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE projects.id = reordered.id;
END;
$function$;

CREATE OR REPLACE FUNCTION reorder_education_for_user(target_user_id integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM education
        WHERE user_id = target_user_id
    )
    UPDATE education
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE education.id = reordered.id;
END;
$function$;

CREATE OR REPLACE FUNCTION reorder_courses_for_user(target_user_id integer)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM courses
        WHERE user_id = target_user_id
    )
    UPDATE courses
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE courses.id = reordered.id;
END;
$function$;

COMMIT;

-- ============================================================
-- Notes for migration to another Postgres provider:
-- 1. No triggers exist in this schema (verified).
-- 2. IDs use GENERATED BY DEFAULT AS IDENTITY instead of Supabase's
--    serial + sequence naming (e.g. secret_key_id_seq) for portability.
--    If you need to preserve exact sequence names/values, adjust accordingly.
-- 3. This schema does NOT include Supabase-specific features:
--    RLS policies, auth schema, storage buckets, or realtime config.
--    Check separately if your app relies on Supabase Auth/Storage/RLS -
--    these will need reimplementation on the new provider.
-- 4. No extensions (e.g. pgcrypto, uuid-ossp) were in use.
-- ============================================================